[package]
name = "octopus_webp"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "octopus_webp"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.29.1"
webp-animation = "0.8.0"
webp = "0.2.4"
